---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Europe/Oslo"
      day: "monday"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "weekly"
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/java"
    registries:
      - artifactory
    schedule:
      interval: "daily"

registries:
  artifactory:
    type: npm-registry
    url: ${{secrets.ARTIFACTORY_URL}}
    username: ${{secrets.ENTUR_ARTIFACTORY_USER}}
    password: ${{secrets.ENTUR_ARTIFACTORY_PASSWORD}}
