---
version: 2
registries:
  jfrog-artifactory:
    type: maven-repository
    url: "https://entur2.jfrog.io/entur2"
    username: ${{secrets.ARTIFACTORY_USER}}
    password: ${{secrets.ARTIFACTORY_TOKEN}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    milestone: 1
    schedule:
      interval: "weekly"
      time: "11:00"
      timezone: "Europe/Oslo"
      day: "tuesday"
    labels:
      - "workflow"
      - "dependencies"
  - package-ecosystem: npm
    directory: "javascript"
    milestone: 1
    groups:
      non-major:
        update-types:
          - "minor"
          - "patch"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    versioning-strategy: increase-if-necessary
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: bundler
    directory: "ruby"
    milestone: 1
    ignore:
      - dependency-name: "business"
        update-types: [version-update:semver-patch]
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    vendor: true
  - package-ecosystem: docker
    directory: "java"
    milestone: 1
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "src/examples/java"
    milestone: 1
    registries:
      - jfrog-artifactory
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Europe/Oslo"
    target-branch: "dependabot_template"
    labels:
      - "java"
      - "dependencies"
