---
version: 2
registries:
  jfrog-artifactory:
    type: maven-repository
    url: "https://entur2.jfrog.io/entur2"
    username: ${{secrets.ENTUR_ARTIFACTORY_USER}}
    password: ${{secrets.ENTUR_ARTIFACTORY_PASSWORD}}
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "11:00"
      timezone: "Europe/Oslo"
      day: "tuesday"
    labels:
      - "workflow"
      - "dependencies"
  - package-ecosystem: npm
    directory: "src/examples/javascript"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: bundler
    directory: "src/examples/ruby"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 0
  - package-ecosystem: docker
    directory: "src/examples/java"
    schedule:
      interval: "weekly"
    labels:
      - "docker"
      - "dependencies"
  - package-ecosystem: "gradle"
    directory: "src/examples/java"
    registries:
      - jfrog-artifactory
    schedule:
      interval: "daily"
      time: "11:00"
      timezone: "Europe/Oslo"
    target-branch: "dependabot_template"
    labels:
      - "java"
      - "dependencies"

